#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

#include "ECSconstantes.hpp"

const unsigned int SPRITE_TILEMAP = 500, WIDTH_SCREEN = 1920, HEIGHT_SCREEN = 1080,
MAX_PLAYER = 4, POSITION_LEVEL_X = 180,POSITION_LEVEL_Y = 70, NUMBR_INPUT = 8,
NUMBR_MAX_FLAG = 6;

const float SIZE_SCALE = 4.0f;
const unsigned int BOMBER_INPUT_COMPONENT = ecs::NUMBER_COMPONENT_BASE_ECS,
BOMBER_MOVEABLE_COMPONENT = ecs::NUMBER_COMPONENT_BASE_ECS + 1,
BOMBER_FLAG_COMPONENT = ecs::NUMBER_COMPONENT_BASE_ECS + 2,
BOMBER_TIMER_COMPONENT = ecs::NUMBER_COMPONENT_BASE_ECS + 3,
BOMBER_TILEMAP_COMPONENT = ecs::NUMBER_COMPONENT_BASE_ECS + 4,
BOMBER_PLAYER_CONFIG_COMPONENT = ecs::NUMBER_COMPONENT_BASE_ECS + 5,
BOMBER_BOMB_CONFIG_COMPONENT = ecs::NUMBER_COMPONENT_BASE_ECS + 6;

const unsigned int INPUT_BOMBER_SYSTEM = ecs::NUMBER_SYSTEM_BASE_ECS,
BOMB_BOMBER_SYSTEM = ecs::NUMBER_SYSTEM_BASE_ECS + 1,
EXPLOSION_BOMBER_SYSTEM = ecs::NUMBER_SYSTEM_BASE_ECS + 2,
TILEMAP_BOMBER_SYSTEM = ecs::NUMBER_SYSTEM_BASE_ECS + 3;

enum
{
	TEXTURE_BOMBERMAN
};

enum
{
    FLAG_SOLID_WALL, FLAG_DESTRUCTIBLE_WALL, FLAG_BOMBERMAN, FLAG_EXPLOSION, FLAG_OBJECT, FLAG_BOMB
};

enum
{
    TILE_SOLID_WALL, TILE_DESTRUCTIBLE_WALL, TILE_EMPTY
};

enum
{
    MOVE_RIGHT, MOVE_LEFT, MOVE_UP, MOVE_DOWN, MOVE_LEFT_UP, MOVE_LEFT_DOWN, MOVE_RIGHT_DOWN, MOVE_RIGHT_UP, LAUNCH_BOMB
};

enum
{
    SPRITE_BOMBERMAN, SPRITE_BOMB
};

enum
{
    EXPLOSION_END_LEFT, EXPLOSION_END_RIGHT, EXPLOSION_CENTER, EXPLOSION_VERTICAL_MIDDLE,
    EXPLOSION_END_UP, EXPLOSION_END_DOWN, EXPLOSION_HORIZONTAL_MIDDLE
};

#endif // CONSTANTS_HPP
