#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

#include "ECSconstantes.hpp"

const unsigned int SPRITE_TILEMAP = 500, WIDTH_SCREEN = 1920, HEIGHT_SCREEN = 1080,
MAX_PLAYER = 4, POSITION_LEVEL_X = 180,POSITION_LEVEL_Y = 70, NUMBR_INPUT = 8,
NUMBR_MAX_FLAG = 6;

const float SIZE_SCALE = 3.0f;
const unsigned int BOMBER_INPUT_COMPONENT = ecs::NUMBER_COMPONENT_BASE_ECS,
BOMBER_MOVEABLE_COMPONENT = ecs::NUMBER_COMPONENT_BASE_ECS + 1,
BOMBER_FLAG_COMPONENT = ecs::NUMBER_COMPONENT_BASE_ECS + 2;
const unsigned int INPUT_BOMBER_SYSTEM = ecs::NUMBER_SYSTEM_BASE_ECS;

enum{
	TEXTURE_BOMBERMAN
};

enum{
	FLAG_DESTRUCTIBLE_WALL, FLAG_SOLID_WALL, FLAG_BOMBERMAN, FLAG_EXPLOSION, FLAG_OBJECT, FLAG_BOMB
};

enum{
	MOVE_RIGHT, MOVE_LEFT, MOVE_UP, MOVE_DOWN, LAUNCH_BOMB
};


#endif // CONSTANTS_HPP
