#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

const unsigned int SPRITE_TILEMAP = 500, WIDTH_SCREEN = 1920, HEIGHT_SCREEN = 1080,
MAX_PLAYER = 4, POSITION_LEVEL_X = 180,POSITION_LEVEL_Y = 70;

const float SIZE_SCALE = 3.0f;
enum{
	TEXTURE_BOMBERMAN
};


#endif // CONSTANTS_HPP
